<?php 

return [

    'trips' => [
        [
            'title' => 'Viaggio in Costarica',
            'place' => 'Costarica',
            'price' => 499,90,
            'image' => 'https://millionaire.it/wp-content/uploads/2016/05/costarica-generica.jpg',
            'starting_date' => '2022-08-02',
            'ending_date' => '2022-08-11',
            'max_participants' => 4,
            //'discount' => '',
            //'is_available' => 1,
        ],
        [
            'title' => 'Weekend in Honduras',
            'place' => 'Honduras, Cuba',
            'price' => 899,90,
            'image' => 'https://www.columbusassicurazioni.it/media/30879/t2.jpg',
            'starting_date' => '2022-07-03',
            'ending_date' => '2022-07-15',
            //'max_participants' => 4,
            'discount' => 10,
            'is_available' => 1,
        ],
        [
            'title' => 'Fuga in Antartide',
            'place' => 'Polo sud',
            'price' => 199,90,
            //'image' => 'https://millionaire.it/wp-content/uploads/2016/05/costarica-generica.jpg',
            'starting_date' => '2023-02-06',
            'ending_date' => '2023-02-28',
            //'max_participants' => 4,
            'discount' => 20,
            //'is_available' => 1,
        ],
        [
            'title' => 'Viaggettino sciallo a Roma',
            'place' => 'Roma',
            'price' => 399,90,
            'image' => 'https://www.turismoroma.it/sites/default/files/Roma%20in%20breve.jpg',
            'starting_date' => '2022-09-02',
            'ending_date' => '2022-09-11',
            //'max_participants' => 4,
            //'discount' => '',
            'is_available' => 0,
        ],
        [
            'title' => 'Pranzo da Zia Carmela',
            //'place' => 'Costarica',
            'price' => 29,90,
            //'image' => 'https://millionaire.it/wp-content/uploads/2016/05/costarica-generica.jpg',
            'starting_date' => '2022-06-07',
            'ending_date' => '2022-06-07',
            'max_participants' => 13,
            //'discount' => '',
            //'is_available' => 1,
        ],
        [
            'title' => 'Passeggiatina con miocuggino',
            'place' => 'Rebibbia',
            'price' => 19,90,
            //'image' => 'https://millionaire.it/wp-content/uploads/2016/05/costarica-generica.jpg',
            'starting_date' => '2022-11-02',
            'ending_date' => '2022-11-11',
            'max_participants' => 1,
            //'discount' => '',
            'is_available' => 0,
        ],
        [
            'title' => 'Giornata nella fabbrica di cioccolato',
            //'place' => 'Costarica',
            'price' => 200,00,
            'image' => 'https://www.mistermovie.it/wp-content/uploads/2016/05/Toothsome-Chocolate-Factory-apre-la-Fabbrica-di-Cioccolato-di-Willy-Wonka-3.jpg',
            'starting_date' => '2022-08-02',
            'ending_date' => '2022-08-02',
            //'max_participants' => 4,
            'discount' => 20,
            'is_available' => 1,
        ],
        [
            'title' => 'Vacanza a Riccione',
            'place' => 'Riccione, Rimini, Ravenna',
            'price' => 300,00,
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/6/68/La_costa_di_Riccione.jpg',
            'starting_date' => '2022-08-02',
            'ending_date' => '2022-08-11',
            'max_participants' => 8,
            //'discount' => '',
            //'is_available' => 1,
        ]
    ]

];